name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt --check
    - name: clippy
      run: cargo clippy --all --tests --all-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose
        cargo clean
        cargo test --verbose --manifest-path testcrate/Cargo.toml
